### ISSUE TITLE
error when npm run dev

### ISSUE THREAD

**Issue by Isomorpheus** [pengfu/vue-2048#3]
After:
$ npm run dev

I get: 

> vue-webpack-start@1.0.0 dev /Users/apple/Documents/GitHub/test/vue-2048
> node build/dev-server.js

> Starting dev server...

 ERROR  Failed to compile with 1 errors                                                                                                                                                                                               11:20:48

 error

> Listening at http://localhost:8080

Ay idea what this is causing?

This "run build" first gave also an error but after adding the "static" folder it dit well.

**Comment by imgss** [comment]
maybe you should rename the '**index_template.html**'（under the root directory）  to '**index.html**'

**Comment by Isomorpheus** [comment]
Thanks, that did the job! 

Only 2 minor warnings after compiling about explicit keys in BoardView.vu which I could solve with small changes:
`<template>
    <div class="board"  tabIndex="1">
        <div v-for="r_item in board.cells">
            <cell v-for="c_item in r_item" :key="this.index"></cell>
        </div>
        <tile-view v-for="tile in tiles" :tile="tile" :key="this.index">
        </tile-view>
        <game-end-overlay :board="board" :onrestart="onRestart"></game-end-overlay>
    </div>
</template>`

**Comment by pengfu** [comment]
We have upgrade the project to vue3 & vite now.
